0.9.2 (#64)
YunoHost-Apps/baikal_ynh pull request #66
Opened 2022-04-24 13:02 UTC by ericgaspar

* 0.9.2

2022-04-24 13:02 UTC, ericgaspar commented
!testme

2022-05-20 18:27 UTC, yalh76 requested changes
It seems not to be just a 0.9.2 upgrade as written in the first comment of this PR

2022-05-20 18:37 UTC, ericgaspar commented
yes I could also say `apply example_ynh` but it wouldn't help...

2022-05-21 10:03 UTC, yalh76 requested changes

2022-05-21 10:03 UTC, yalh76 commented on scripts/upgrade
> -	php"${phpversion}" "${final_path}/bin/upgrade.sh"
There is no more need to execute the `/bin/upgrade.sh` script ?
If not, maybe files in `sources/extra_files/app` should be removed

2022-05-21 10:05 UTC, yalh76 commented
> yes I could also say `apply example_ynh` but it wouldn't help...

It helps to understand what you are doing in the PR, and lets know that the review will be hudge

2022-05-21 10:20 UTC, ericgaspar commented
!testme

2022-05-27 21:04 UTC, merged